### ISSUE TITLE
Document how to configure Deluge user/password

### ISSUE THREAD

**Issue by ngosang** [LeiShi1313/downloader-exporter#11]
1. You have to open the file `deluge_folder/auth`
2. The file format is `<user>:<password>:10`
2. Edit the `config.yml` in  downloader-exporter
```yaml
deluge:
    client: deluge
    host: deluge:58846
    username: <user>
    password: <pass>
```
