### ISSUE TITLE
无法使用快校版tr读取信息

### ISSUE THREAD

**Issue by CytsOn** [LeiShi1313/downloader-exporter#8]
你好，作者。感谢你的分享。我在使用downloader-exporter遇到无法使用快校版tr和正常版tr，但能使用qb的问题。希望能够得到解答。
以下是一些具体信息。

```
#config
qb:
  client: qbittorrent
  host: http://192.168.50.100:8999/
  username: admin
  password: *********
tr2:
  client: transmission
  host: 192.168.50.100:9091
  username: admin
  password: *********

#日志报错
| ERROR    | downloader_exporter.transmission_exporter:get_status_metrics:85 - [tr2] Can not get client session: quote() doesn't support 'encoding' for bytes

#页面显示
# HELP downloader_up Whether if server is alive or not
# TYPE downloader_up gauge
downloader_up{client="transmission",host="192.168.50.100:9091",name="tr2",version=""} 0.0
# HELP downloader_download_bytes_total Data downloaded this session (bytes)
# TYPE downloader_download_bytes_total counter
downloader_download_bytes_total{client="transmission",host="192.168.50.100:9091",name="tr2",version=""} 0.0
# HELP downloader_download_speed_bytes Data download speed (bytes)
# TYPE downloader_download_speed_bytes gauge
downloader_download_speed_bytes{client="transmission",host="192.168.50.100:9091",name="tr2",version=""} 0.0
# HELP downloader_upload_bytes_total Data uploaded this session (bytes)
# TYPE downloader_upload_bytes_total counter
downloader_upload_bytes_total{client="transmission",host="192.168.50.100:9091",name="tr2",version=""} 0.0
# HELP downloader_upload_speed_bytes Data upload speed (bytes)
# TYPE downloader_upload_speed_bytes gauge
downloader_upload_speed_bytes{client="transmission",host="192.168.50.100:9091",name="tr2",version=""} 0.0```

**Comment by LeiShi1313** [comment]
tr的版本告知一下吧

**Comment by CytsOn** [comment]
chisbread/transmission r11。在将tr纯数字密码修改前后带字母、tr重启、重新生成容器等一系列尝试是后，好了，也不知道怎么好。😂

**Comment by xuxiaohu6** [comment]
> 

我也出现了这种情况，客户端是transmission，密码也是纯数字，在  
   password: *********  
这里，我用”“把数字引起来就好了。

**Comment by xinmans** [comment]
chisbread/transmission
这个版本 tr也报错

 [tr] Can not get client torrents: transmission daemon require auth
downloader-exporter  | 2025-01-08 09:34:13.759 | ERROR    | downloader_exporter.transmission_exporter:get_status_metrics:85 - [tr-dingyue] Can not get client session: transmission daemon require auth

downloader_upload_speed_bytes{client="transmission",host="192.168.31.10:9091",name="tr",version=""} 0.0

```
services:
  transmission:
    image: chisbread/transmission
    container_name: transmission
    environment:
- PUID=1001
- PGID=1001
- TZ=Asia/Shanghai
- USER=admin
- PASS=adminadmin
- PEERPORT=10413
    volumes:

    ports:
- 9091:9091
- 10413:10413
- 10413:10413/udp
    restart: unless-stopped

```

**Comment by LeiShi1313** [comment]
请升级到`0.5.2`之后再尝试下

**Comment by xinmans** [comment]
> 请升级到`0.5.2`之后再尝试下

已经升级，但是还是报错
```

downloader-exporter  | 2025-01-14 10:16:27.794 | ERROR    | downloader_exporter.transmission_exporter:get_status_metrics:86 - [tr] Can not get client session: transmission daemon require auth
downloader-exporter  | 2025-01-14 10:16:36.635 | ERROR    | downloader_exporter.transmission_exporter:get_torrent_metrics:136 - [tr] Can not get client torrents: transmission daemon require auth
downloader-exporter  | 2025-01-14 10:16:36.656 | ERROR    | downloader_exporter.transmission_exporter:get_status_metrics:86 - [tr-dingyue] Can not get client session: transmission daemon require auth
downloader-exporter  | 2025-01-14 10:16:36.680 | ERROR    | downloader_exporter.transmission_exporter:get_torrent_metrics:136 - [tr-dingyue] Can not get client torrents: transmission daemon require auth
^Ccanceled

```
config
```

tr:
    client: transmission
    host: 192.168.31.10:9091
    username: amdin
    password: adminadmin
tr-dingyue:
    client: transmission
    host: 192.168.31.10:9092
    username: amdin
    password: adminadmin


```
